 variable "region" {}
 variable "main_vpc_cidr" {}
 variable "public_subnet1" {}
 variable "private_subnet1" {}
 variable "zone1" {}
 variable "zone2" {}
 variable "bast_inst_type" {}
 variable "mysql_inst_type" {}
 variable "jenkins_inst_type" {}
 variable "web_inst_type" {}
 variable "key" {}